-- MySQL Script generated by MySQL Workbench
-- 05/19/16 11:09:32
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sape
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sape
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sape` DEFAULT CHARACTER SET utf8 ;
USE `sape` ;

-- -----------------------------------------------------
-- Table `sape`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sape`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NULL,
  `senha` VARCHAR(255) NULL,
  `isProfCoordenadorLei` TINYINT(1) NULL,
  `isAdmin` TINYINT(1) NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sape`.`Regional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sape`.`Regional` (
  `idRegional` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL,
  PRIMARY KEY (`idRegional`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sape`.`Post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sape`.`Post` (
  `idPost` INT NOT NULL AUTO_INCREMENT,
  `idProfessor` INT NULL,
  `mensagem` MEDIUMTEXT NULL,
  `data` DATETIME NULL,
  PRIMARY KEY (`idPost`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sape`.`Professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sape`.`Professor` (
  `idProfessor` INT NOT NULL AUTO_INCREMENT,
  `idRegional` INT NOT NULL,
  `idUsuario` INT NULL,
  `nome` VARCHAR(255) NULL,
  PRIMARY KEY (`idProfessor`),
  INDEX `FK_Professor_Usuario_idx` (`idUsuario` ASC),
  INDEX `FK_Professor_regional_idx` (`idRegional` ASC),
  CONSTRAINT `FK_Professor_Usuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `sape`.`Usuario` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Professor_regional`
    FOREIGN KEY (`idRegional`)
    REFERENCES `sape`.`Regional` (`idRegional`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Professor_post`
    FOREIGN KEY (`idProfessor`)
    REFERENCES `sape`.`Post` (`idPost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sape`.`Escola`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sape`.`Escola` (
  `idEscola` INT NOT NULL AUTO_INCREMENT,
  `idRegional` INT NULL,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`idEscola`),
  INDEX `FK_escola_regional_idx` (`idRegional` ASC),
  CONSTRAINT `FK_escola_regional`
    FOREIGN KEY (`idRegional`)
    REFERENCES `sape`.`Regional` (`idRegional`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sape`.`Aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sape`.`Aluno` (
  `idAluno` INT NOT NULL AUTO_INCREMENT,
  `idEscola` INT NOT NULL,
  `nome` VARCHAR(255) NULL,
  PRIMARY KEY (`idAluno`),
  INDEX `FK_aluno_escola_idx` (`idEscola` ASC),
  CONSTRAINT `FK_aluno_escola`
    FOREIGN KEY (`idEscola`)
    REFERENCES `sape`.`Escola` (`idEscola`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sape`.`Imagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sape`.`Imagem` (
  `idImagem` INT NOT NULL AUTO_INCREMENT,
  `idPost` INT NOT NULL,
  `linkImagem` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idImagem`),
  INDEX `FK_imagem_post_idx` (`idPost` ASC),
  CONSTRAINT `FK_imagem_post`
    FOREIGN KEY (`idPost`)
    REFERENCES `sape`.`Post` (`idPost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sape`.`Avaliacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sape`.`Avaliacao` (
  `idAvaliacao` INT NOT NULL AUTO_INCREMENT,
  `ano` DATE NULL,
  `data` DATETIME NOT NULL,
  `periodo` INT NULL,
  `idAluno` INT NOT NULL,
  PRIMARY KEY (`idAvaliacao`),
  INDEX `FK_avaliacao_aluno_idx` (`idAluno` ASC),
  CONSTRAINT `FK_avaliacao_aluno`
    FOREIGN KEY (`idAluno`)
    REFERENCES `sape`.`Aluno` (`idAluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- em 08/06/2016
ALTER TABLE `sape`.`usuario` 
ADD COLUMN `isProfessor` TINYINT(1) NULL AFTER `isAdmin`;

-- em 16/06/2016, tabela professor agora é pclei
ALTER TABLE `sape`.`professor` 
RENAME TO  `sape`.`pclei` ;

-- em 23/06/2016, criacao da tabela de funcao de usuario / user roles
CREATE TABLE IF NOT EXISTS `sape`.`usuario_funcao` (
  `idUsuario` INT NOT NULL,
  `funcao` VARCHAR(10) NOT NULL DEFAULT 'PCLEI',
  PRIMARY KEY (`idUsuario`, `funcao`),
  CONSTRAINT `FK_usuario_usuario_funcao`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `sape`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
    
   -- em 10/08/2016
   
ALTER TABLE `sape`.`avaliacao` 
ADD COLUMN `nivel` TINYINT(1) NULL AFTER `idAluno`;

ALTER TABLE `sape`.`avaliacao` ADD COLUMN `nomeAluno` TINYINT(1) NULL AFTER `nivel`;
